<a href="https://colab.research.google.com/github/noohamol-km/data-science/blob/main/program3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [9]:
# Creating a 1D array
array = np.arange(12)
print("Original array:", array)
# Reshaping to 2D array (3x4)
reshaped_array = array.reshape((3, 4))
print("Reshaped to 3x4:\n", reshaped_array)
# Reshaping to 3D array (2x3x2)
reshaped_array_3d = array.reshape((2, 3, 2))
print("Reshaped to 2x3x2:\n", reshaped_array_3d)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x3x2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
