<a href="https://colab.research.google.com/github/noohamol-km/data-science/blob/main/program1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array_from_list = np.array([1,2,3,4,5])
print("array from list:",array_from_list)

array from list: [1 2 3 4 5]


In [4]:
array_with_range = np.arange(10)
print("array with range:",array_with_range)

array with range: [0 1 2 3 4 5 6 7 8 9]


In [5]:
zeros_array = np.zeros((3, 3))
print("Array of zeros:\n", zeros_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
zeros_array = np.zeros((3, 3))
print("Array of zeros:\n", zeros_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
